### ISSUE TITLE
Porthole is not working

### ISSUE THREAD

**Issue by bkt92** [wildfoundry/dataplicity-porthole-releases#27]
I am very excited when I heard what porthole can do. But when I install it ops, it's not working, so disappointed. 
<img width="605" alt="annotation1" src="https://user-images.githubusercontent.com/3808392/47300663-45fc8800-d647-11e8-972b-f3bc23a97119.png">
<img width="602" alt="annotation2" src="https://user-images.githubusercontent.com/3808392/47300664-45fc8800-d647-11e8-867e-b5eb9fdf3a7f.png">
Why why ...

**Comment by barfle** [comment]
Hi there,
We've just released a new version that fixes this issue for some accounts.  Can you please give it another try with the latest version here?  

https://github.com/wildfoundry/dataplicity-porthole-releases/releases/download/1.49.24.4/DataplicityPortholeSetup.msi

Best,
Elliot

**Comment by barfle** [comment]
Hi there,
We're assuming this is fixed now but please feel free to reopen if you continue to encounter issues.
Best,
Elliot.

**Comment by bkt92** [comment]
Ok, It's working now. Thank you !!!
