### ISSUE TITLE
Getting "Server unexpectedly closed network connection"

### ISSUE THREAD

**Issue by DaLooK** [wildfoundry/dataplicity-porthole-releases#29]
I've just downloaded and installed Porthole from the Dataplicity [page](https://www.dataplicity.com/apps/porthole/).
That version right now is outdated. Downloaded the latest version from within the Porthole app.
Followed [this guide](https://docs.dataplicity.com/docs/redirect-tcp-ports-over-the-internet), entered my credentials, selected my device, chose my port, tried connecting with Putty, and nothing.
Then tried connecting with Filezilla and got the same result.
Tried changing the port multiple times, yet the same result.

Here's a screenshot.
![porthole error](https://user-images.githubusercontent.com/7662026/47466829-d1495b00-d7b8-11e8-8cd0-d52758cae7eb.png)

**Comment by DaLooK** [comment]
Okay.
Today I've tried connecting once again. This time it worked.
Don't know what changed.

This was a false alarm. Sorry about that.

**Comment by barfle** [comment]
I'm afraid that was probably another bug our side :(. But we found it and fixed it, sorry for inconvenience.

**Comment by rafaolivas** [comment]
This is currently happening to me randomly in version 1.51.24.4. Is there any workaround?

**Comment by rafaolivas** [comment]
I restarted the "Dataplicity Porthole Service" and it is working now

**Comment by EmanuelAlexandru** [comment]
> I restarted the "Dataplicity Porthole Service" and it is working now

Thank you, it worked when nothing else did.
