### ISSUE TITLE
Porthole does not work for the moment version 1.51.24.4

### ISSUE THREAD

**Issue by InfernoSpoo** [wildfoundry/dataplicity-porthole-releases#35]
Hi,
I installed porthole 1.51.24.4 in a windows computer. Thanks to dataplicity, I successed to reach a raspberry connected via a 4G modem but I 'm stuck with reaching the raspberry via ssh thanks to porthole. Putty(sftp, localhost, port 10123) is showing immediately a pop up windows:the server closed connection.
Do you have any idea on that?

Thanks in advance,
David

**Comment by Radoslaw-K** [comment]
Hey @InfernoSpoo ,

Could you message us on intercom please? It's the live chat that is available on dataplicity.com 

Best regards,
Radoslav

**Comment by InfernoSpoo** [comment]
ok thank you
