### ISSUE TITLE
Porthole Dropping Connection

### ISSUE THREAD

**Issue by joaodiogoamaral** [wildfoundry/dataplicity-porthole-releases#38]
Recently, on my Windows PC, I am not able to connect to any device using Porthole by SSHing to my LO address. The devices however, show up online on my browser and I can access the console without any problem. Please advise.

**Comment by PawelErnestLuczak** [comment]
Could you please paste the result of ssh -v user@localhost -p <redirected> ?

**Comment by joaodiogoamaral** [comment]
Czesc Pawel, 

PS C:\Users\ja> ssh -v pi@localhost -p 12345
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug1: Connecting to localhost [::1] port 12345.
debug1: connect to address ::1 port 12345: Connection refused
debug1: Connecting to localhost [127.0.0.1] port 12345.
debug1: Connection established.
debug1: identity file C:\\Users\\ja/.ssh/id_rsa type -1
debug1: identity file C:\\Users\\ja/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\ja/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\ja/.ssh/id_dsa-cert type -1
debug1: identity file C:\\Users\\ja/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\ja/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\ja/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\ja/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\ja/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\ja/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
kex_exchange_identification: Connection closed by remote host
PS C:\Users\ja>



Seems it is missing some certificates, could it be?

**Comment by PawelErnestLuczak** [comment]
we are having the same issue for raspberry device. It works for all other device types and the kex problem is happening only on windows SSH client + raspberry. We are investigating the issue.

**Comment by joaodiogoamaral** [comment]
OK, I will be waiting developments then.

**Comment by PawelErnestLuczak** [comment]
Which ports are you assigning the devices to? Is that the all of the devices stopped communicating via SSH or just some part of them? We have found that problems are occurring for ports above 10010.

**Comment by PawelErnestLuczak** [comment]
@joaodiogoamaral Hi, we have just released an update, please check your redirects with it

**Comment by joaodiogoamaral** [comment]
Hi @PawelErnestLuczak , I didn't do extensive tests, but I can access my devices with higher port numbers. Thank you for your support, I'll let you know if I run into any issues.
